name: Cloud189Checkin

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: 0 1,11 * * *

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Python
      run: |
        sudo apt update && \
        sudo apt install python3
      
    - name: requirements
      run: |
        pip3 install -r requirements.txt
        
    - name: Checkin
      env:
        CLOUD189_USERNAME: ${{ secrets.CLOUD189_USERNAME }}
        CLOUD189_PASSWD: ${{ secrets.CLOUD189_PASSWD }}
        SCKEY: ${{ secrets.SCKEY }}
      run: |
        python3 C189Checkin.py
